-- ============================================================
-- CUCCU-POS: expenses table for Sales & Expenses page (002)
-- Run ONCE in Supabase Dashboard -> SQL Editor, AFTER 001.
-- Safe to re-run. Cash-only scope; owner-managed ledger.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    description text NOT NULL,
    category text NOT NULL DEFAULT 'Other',
    amount numeric(10,2) NOT NULL,
    expense_type text NOT NULL DEFAULT 'One-Time',
    frequency text NOT NULL DEFAULT 'One-Time',
    source text NOT NULL DEFAULT 'Cash on Hand',
    date_incurred date NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Manila')::date,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT expenses_amount_check CHECK (amount > 0),
    CONSTRAINT expenses_category_check CHECK (
        category IN ('Ingredients','Packaging','Utilities','Rent','Labor','Other')
    ),
    CONSTRAINT expenses_type_check CHECK (
        expense_type IN ('Recurring','One-Time')
    )
);

ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owners can manage expenses" ON public.expenses;
CREATE POLICY "Owners can manage expenses"
ON public.expenses
FOR ALL
TO authenticated
USING (public.get_user_role() = 'owner')
WITH CHECK (public.get_user_role() = 'owner');

GRANT SELECT, INSERT, UPDATE, DELETE ON public.expenses TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.expenses_id_seq TO authenticated;

CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(date_incurred);
CREATE INDEX IF NOT EXISTS idx_expenses_category ON public.expenses(category);
